# Form implementation generated from reading ui file 'image_display.py'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ImageDisplay(object):
    def setupUi(self, ImageDisplay):
        ImageDisplay.setObjectName("ImageDisplay")
        ImageDisplay.resize(1000, 1000)
        ImageDisplay.setMinimumSize(QtCore.QSize(1000, 1000))
        self.pos = QtWidgets.QLabel(parent=ImageDisplay)
        self.pos.setGeometry(QtCore.QRect(10, 10, 53, 16))
        self.pos.setText("")
        self.pos.setObjectName("pos")

        self.retranslateUi(ImageDisplay)
        QtCore.QMetaObject.connectSlotsByName(ImageDisplay)

    def retranslateUi(self, ImageDisplay):
        _translate = QtCore.QCoreApplication.translate
        ImageDisplay.setWindowTitle(_translate("ImageDisplay", "Form"))
