# Form implementation generated from reading ui file 'soft_status.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_SoftStatus(object):
    def setupUi(self, SoftStatus):
        SoftStatus.setObjectName("SoftStatus")
        SoftStatus.resize(998, 33)
        SoftStatus.setMinimumSize(QtCore.QSize(998, 33))
        self.gridLayout = QtWidgets.QGridLayout(SoftStatus)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.total_receive = QtWidgets.QLabel(parent=SoftStatus)
        self.total_receive.setMinimumSize(QtCore.QSize(100, 33))
        self.total_receive.setObjectName("total_receive")
        self.gridLayout.addWidget(self.total_receive, 0, 6, 1, 1)
        self.send_speed = QtWidgets.QLabel(parent=SoftStatus)
        self.send_speed.setMinimumSize(QtCore.QSize(100, 33))
        self.send_speed.setObjectName("send_speed")
        self.gridLayout.addWidget(self.send_speed, 0, 4, 1, 1)
        self.total_send_text = QtWidgets.QLabel(parent=SoftStatus)
        self.total_send_text.setMinimumSize(QtCore.QSize(100, 33))
        self.total_send_text.setObjectName("total_send_text")
        self.gridLayout.addWidget(self.total_send_text, 0, 3, 1, 1)
        self.receive_speed = QtWidgets.QLabel(parent=SoftStatus)
        self.receive_speed.setMinimumSize(QtCore.QSize(100, 33))
        self.receive_speed.setObjectName("receive_speed")
        self.gridLayout.addWidget(self.receive_speed, 0, 8, 1, 1)
        self.connect_status = QtWidgets.QLabel(parent=SoftStatus)
        self.connect_status.setMinimumSize(QtCore.QSize(100, 33))
        self.connect_status.setObjectName("connect_status")
        self.gridLayout.addWidget(self.connect_status, 0, 0, 1, 1)
        self.total_receive_text = QtWidgets.QLabel(parent=SoftStatus)
        self.total_receive_text.setMinimumSize(QtCore.QSize(99, 33))
        self.total_receive_text.setObjectName("total_receive_text")
        self.gridLayout.addWidget(self.total_receive_text, 0, 7, 1, 1)
        self.total_send = QtWidgets.QLabel(parent=SoftStatus)
        self.total_send.setMinimumSize(QtCore.QSize(99, 33))
        self.total_send.setObjectName("total_send")
        self.gridLayout.addWidget(self.total_send, 0, 2, 1, 1)
        self.connect_status_text = QtWidgets.QLabel(parent=SoftStatus)
        self.connect_status_text.setMinimumSize(QtCore.QSize(100, 33))
        self.connect_status_text.setObjectName("connect_status_text")
        self.gridLayout.addWidget(self.connect_status_text, 0, 1, 1, 1)
        self.send_speed_text = QtWidgets.QLabel(parent=SoftStatus)
        self.send_speed_text.setMinimumSize(QtCore.QSize(100, 33))
        self.send_speed_text.setObjectName("send_speed_text")
        self.gridLayout.addWidget(self.send_speed_text, 0, 5, 1, 1)
        self.receive_speed_text = QtWidgets.QLabel(parent=SoftStatus)
        self.receive_speed_text.setMinimumSize(QtCore.QSize(100, 33))
        self.receive_speed_text.setObjectName("receive_speed_text")
        self.gridLayout.addWidget(self.receive_speed_text, 0, 9, 1, 1)

        self.retranslateUi(SoftStatus)
        QtCore.QMetaObject.connectSlotsByName(SoftStatus)

    def retranslateUi(self, SoftStatus):
        _translate = QtCore.QCoreApplication.translate
        SoftStatus.setWindowTitle(_translate("SoftStatus", "Form"))
        self.total_receive.setText(_translate("SoftStatus", "已接收字节:"))
        self.send_speed.setText(_translate("SoftStatus", "发送速度:"))
        self.total_send_text.setText(_translate("SoftStatus", "0"))
        self.receive_speed.setText(_translate("SoftStatus", "接受速度:"))
        self.connect_status.setText(_translate("SoftStatus", "连接状态："))
        self.total_receive_text.setText(_translate("SoftStatus", "0"))
        self.total_send.setText(_translate("SoftStatus", "已发送字节:"))
        self.connect_status_text.setText(_translate("SoftStatus", "未连接"))
        self.send_speed_text.setText(_translate("SoftStatus", "0字节/s"))
        self.receive_speed_text.setText(_translate("SoftStatus", "0字节/s"))
