# Form implementation generated from reading ui file 'tcp_config_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_TCPConfigWidget(object):
    def setupUi(self, TCPConfigWidget):
        TCPConfigWidget.setObjectName("TCPConfigWidget")
        TCPConfigWidget.resize(200, 362)
        TCPConfigWidget.setMinimumSize(QtCore.QSize(200, 85))
        TCPConfigWidget.setMaximumSize(QtCore.QSize(200, 362))
        self.gridLayout_2 = QtWidgets.QGridLayout(TCPConfigWidget)
        self.gridLayout_2.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.remote_ip_edit = QtWidgets.QLineEdit(parent=TCPConfigWidget)
        self.remote_ip_edit.setObjectName("remote_ip_edit")
        self.gridLayout.addWidget(self.remote_ip_edit, 0, 1, 1, 1)
        self.remote_port_label = QtWidgets.QLabel(parent=TCPConfigWidget)
        self.remote_port_label.setObjectName("remote_port_label")
        self.gridLayout.addWidget(self.remote_port_label, 1, 0, 1, 1)
        self.local_port_label = QtWidgets.QLabel(parent=TCPConfigWidget)
        self.local_port_label.setObjectName("local_port_label")
        self.gridLayout.addWidget(self.local_port_label, 2, 0, 1, 1)
        self.client_mode_button = QtWidgets.QRadioButton(parent=TCPConfigWidget)
        self.client_mode_button.setChecked(True)
        self.client_mode_button.setObjectName("client_mode_button")
        self.gridLayout.addWidget(self.client_mode_button, 3, 0, 1, 2)
        self.remote_ip_label = QtWidgets.QLabel(parent=TCPConfigWidget)
        self.remote_ip_label.setMinimumSize(QtCore.QSize(51, 0))
        self.remote_ip_label.setObjectName("remote_ip_label")
        self.gridLayout.addWidget(self.remote_ip_label, 0, 0, 1, 1)
        self.local_port_edit = QtWidgets.QLineEdit(parent=TCPConfigWidget)
        self.local_port_edit.setObjectName("local_port_edit")
        self.gridLayout.addWidget(self.local_port_edit, 2, 1, 1, 1)
        self.remote_port_edit = QtWidgets.QLineEdit(parent=TCPConfigWidget)
        self.remote_port_edit.setObjectName("remote_port_edit")
        self.gridLayout.addWidget(self.remote_port_edit, 1, 1, 1, 1)
        self.server_mode_button = QtWidgets.QRadioButton(parent=TCPConfigWidget)
        self.server_mode_button.setObjectName("server_mode_button")
        self.gridLayout.addWidget(self.server_mode_button, 4, 0, 1, 2)
        self.client_show_view = QtWidgets.QTableView(parent=TCPConfigWidget)
        self.client_show_view.setEnabled(False)
        self.client_show_view.setMaximumSize(QtCore.QSize(190, 220))
        self.client_show_view.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.client_show_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.client_show_view.setObjectName("client_show_view")
        self.client_show_view.horizontalHeader().setStretchLastSection(False)
        self.client_show_view.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.client_show_view, 5, 0, 2, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(TCPConfigWidget)
        self.client_mode_button.clicked.connect(TCPConfigWidget.set_client_mode) # type: ignore
        self.server_mode_button.clicked.connect(TCPConfigWidget.set_server_mode) # type: ignore
        self.client_show_view.clicked['QModelIndex'].connect(TCPConfigWidget.set_select_host) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TCPConfigWidget)

    def retranslateUi(self, TCPConfigWidget):
        _translate = QtCore.QCoreApplication.translate
        TCPConfigWidget.setWindowTitle(_translate("TCPConfigWidget", "Form"))
        self.remote_ip_edit.setText(_translate("TCPConfigWidget", "192.168.1.1"))
        self.remote_port_label.setText(_translate("TCPConfigWidget", "远程端口"))
        self.local_port_label.setText(_translate("TCPConfigWidget", "本地端口"))
        self.client_mode_button.setText(_translate("TCPConfigWidget", "客户端"))
        self.remote_ip_label.setText(_translate("TCPConfigWidget", "远程地址"))
        self.local_port_edit.setText(_translate("TCPConfigWidget", "8080"))
        self.remote_port_edit.setText(_translate("TCPConfigWidget", "8080"))
        self.server_mode_button.setText(_translate("TCPConfigWidget", "服务端"))
