# Form implementation generated from reading ui file 'tcp_config_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore


class Ui_TCPConfigWidget(object):
    def setupUi(self, TCPConfigWidget):
        TCPConfigWidget.setObjectName("TCPConfigWidget")
        TCPConfigWidget.resize(400, 300)

        self.retranslateUi(TCPConfigWidget)
        QtCore.QMetaObject.connectSlotsByName(TCPConfigWidget)

    def retranslateUi(self, TCPConfigWidget):
        _translate = QtCore.QCoreApplication.translate
        TCPConfigWidget.setWindowTitle(_translate("TCPConfigWidget", "Form"))
