# Form implementation generated from reading ui file 'udp_config_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore


class Ui_UDPConfigWidget(object):
    def setupUi(self, UDPConfigWidget):
        UDPConfigWidget.setObjectName("UDPConfigWidget")
        UDPConfigWidget.resize(400, 300)

        self.retranslateUi(UDPConfigWidget)
        QtCore.QMetaObject.connectSlotsByName(UDPConfigWidget)

    def retranslateUi(self, UDPConfigWidget):
        _translate = QtCore.QCoreApplication.translate
        UDPConfigWidget.setWindowTitle(_translate("UDPConfigWidget", "Form"))
